---
title: "Assignment 1: Introduction"
author: "Nagarajan Vaidya Subramanian"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assigment section on Sakai.


## 1) Finish setting up R Studio

### Install TinyTex
Now, run this code cell the same way. This will install "tinytex" -- a helper app that allows you to knit your markdown documents into professional quality PDFs.
```{r install tiny tex, eval=FALSE, include=FALSE}
#install tinytext
tinytex::install_tinytex()
```

### Set your default knit directory
This setting will help deal with relative paths later on...
 - From the Tool menu, select `Global Options`
 - Select the RMarkdown section
 - In the "Evaluate chunks in directory", set the option to "Project"


## 2) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: My first experience with R was during my undergrad Statistics class, but that was a few years ago. As an MEM student, I took ENV 710 Applied Statistical Modelling last semester which is the first time I used R Studio. That class, along with ENV 716 Energy Modelling, were my first formal training in the field of data analytics (broadly). As for Git, I'm familiar with what it is used for and who uses it but have not used it myself till now. Excited to get formal training in these skills and tools and for my first formal training in the field of Data Analytics itself!

2. Are there any components of the course about which you feel confident?

> Answer: About half of the modules of this course overlap with what was covered in ENV 710 (sourcing data, data wrangling, creating models, interpretation). So I feel confident about these more technical aspects. I look forward to learning to use these skills for the purpose of analysing data in a broader context, and hopefully, in energy-related contexts too.

3. Are there any components of the course about which you feel apprehensive?

> Answer: My experience with R Studio showed me that the tool can sometimes behave unpredictably and throw errors that are challenging to resolve. ALso, learning to go beyond the context of the data itself and putting in a big picture, quantifying and interpreting the results are some aspects of this subject that I need to learn to do better.


## 3) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/nagarajan-vs/EDA-Spring2023

## 4) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Sakai. 
